server:
  port: ":8080"
  mode: "debug"

database:
  host: "localhost"
  port: "49311"
  name: "product_configurator"
  user: "root"
  password: "root"
  sslmode: "disable"

cors:
  allow_origins:
#    - "*"
    - "http://localhost:9001"
    - "http://localhost:8080"
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"
  expose_headers:
    - "Content-Length"
  allow_credentials: true
  max_age: "12h"