definitions:
  models.Attribute:
    properties:
      category:
        $ref: '#/definitions/models.AttributeCategory'
      categoryID:
        type: integer
      code:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      order:
        type: integer
    type: object
  models.AttributeCategory:
    properties:
      code:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  models.DenyRule:
    properties:
      code:
        type: string
      id:
        type: integer
      isGlobal:
        type: boolean
      name:
        type: string
      productPart:
        $ref: '#/definitions/models.ProductPart'
      productPartID:
        type: integer
    type: object
  models.Product:
    properties:
      cloud_lab_id:
        type: integer
      code:
        type: string
      created_at:
        type: string
      default_quantity:
        type: integer
      description:
        type: string
      enable_custom_format:
        type: boolean
      enable_custom_quantity:
        type: boolean
      id:
        type: integer
      maximum_quantity:
        type: integer
      minimum_quantity:
        type: integer
      name:
        type: string
      packing_unit:
        type: integer
      price_calculation_type:
        type: string
      time_to_produce:
        type: string
      type:
        type: string
      updated_at:
        type: string
    type: object
  models.ProductPart:
    properties:
      code:
        type: string
      content_type:
        type: string
      deny_rules:
        items:
          $ref: '#/definitions/models.DenyRule'
        type: array
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /attributes/:
    get:
      description: Retrieve a list of all attributes
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of items per page
        in: query
        name: page_size
        type: integer
      - description: Search term for filtering by name or code
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Attribute'
            type: array
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Get all attribute
      tags:
      - Attributes
    post:
      consumes:
      - application/json
      description: Create a attribute with the provided JSON payload
      parameters:
      - description: Attribute data
        in: body
        name: Attribute
        required: true
        schema:
          $ref: '#/definitions/models.Attribute'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Attribute'
        "400":
          description: Bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Create a new attribute
      tags:
      - Attributes
  /attributes/{id}:
    delete:
      description: Delete a single attribute by its ID
      parameters:
      - description: Attribute ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Attribute deleted successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid ID
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Delete an attribute by ID
      tags:
      - Attributes
    get:
      description: Get a single attribute by its ID
      parameters:
      - description: Attribute ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Attribute'
        "400":
          description: Invalid ID
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Attribute not found
          schema:
            additionalProperties: true
            type: object
      summary: Get Attribute by ID
      tags:
      - Attributes
    put:
      consumes:
      - application/json
      description: Update the details of an existing attribute by providing the updated
        JSON payload
      parameters:
      - description: Updated Attribute data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Attribute'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Attribute'
        "400":
          description: Bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Update an existing attribute
      tags:
      - Attributes
  /deny-rules/:
    get:
      description: Retrieve a list of all deny rules
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of items per page
        in: query
        name: page_size
        type: integer
      - description: Search term for filtering by name or code
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.DenyRule'
            type: array
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Get all deny rules
      tags:
      - DenyRule
    post:
      consumes:
      - application/json
      description: Create a deny rule with the provided JSON payload
      parameters:
      - description: Deny Rule data
        in: body
        name: denyRule
        required: true
        schema:
          $ref: '#/definitions/models.DenyRule'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DenyRule'
        "400":
          description: Bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Create a new deny rule
      tags:
      - DenyRule
  /deny-rules/{id}:
    delete:
      description: Delete a single deny rule by its ID
      parameters:
      - description: Deny Rule ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Product deleted successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid ID
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Delete a deny rule by ID
      tags:
      - DenyRule
    get:
      description: Get a single Deny Rule by its ID
      parameters:
      - description: Deny Rule ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DenyRule'
        "400":
          description: Invalid ID
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Deny Rule not found
          schema:
            additionalProperties: true
            type: object
      summary: Get Deny Rule by ID
      tags:
      - DenyRule
    put:
      consumes:
      - application/json
      description: Update the details of an existing deny rule by providing the updated
        JSON payload
      parameters:
      - description: Updated deny rule data
        in: body
        name: denyRule
        required: true
        schema:
          $ref: '#/definitions/models.DenyRule'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DenyRule'
        "400":
          description: Bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Update an existing deny rule
      tags:
      - DenyRule
  /product-parts/:
    get:
      description: Retrieve a list of all product parts
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of items per page
        in: query
        name: page_size
        type: integer
      - description: Search term for filtering by name or code
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ProductPart'
            type: array
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Get all product parts
      tags:
      - ProductPart
    post:
      consumes:
      - application/json
      parameters:
      - description: Product Part data
        in: body
        name: productPart
        required: true
        schema:
          $ref: '#/definitions/models.ProductPart'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ProductPart'
        "400":
          description: Bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Create a new product part
      tags:
      - ProductPart
  /product-parts/{id}:
    delete:
      description: Delete a single product part by its ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Product deleted successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid ID
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Delete a product part by ID
      tags:
      - ProductPart
    get:
      description: Get a single Product Part by its ID
      parameters:
      - description: Product Part ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ProductPart'
        "400":
          description: Invalid ID
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Product Part not found
          schema:
            additionalProperties: true
            type: object
      summary: Get Product Part by ID
      tags:
      - ProductPart
    put:
      consumes:
      - application/json
      description: Update the details of an existing product part by providing the
        updated JSON payload
      parameters:
      - description: Updated product data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.ProductPart'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ProductPart'
        "400":
          description: Bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Update an existing product part
      tags:
      - ProductPart
  /products/:
    get:
      description: Retrieve a list of all products
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of items per page
        in: query
        name: page_size
        type: integer
      - description: Search term for filtering by name or code
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Get all products
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Create a product with the provided JSON payload
      parameters:
      - description: Product data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Create a new product
      tags:
      - Products
  /products/{id}:
    delete:
      description: Delete a single product by its ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Product deleted successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid ID
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Delete a product by ID
      tags:
      - Products
    get:
      description: Get a single product by its ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "404":
          description: Product not found
          schema:
            additionalProperties: true
            type: object
      summary: Get product by ID
      tags:
      - Products
    put:
      consumes:
      - application/json
      description: Update the details of an existing product by providing the updated
        JSON payload
      parameters:
      - description: Updated product data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Update an existing product
      tags:
      - Products
swagger: "2.0"
